feat: add gemini vertex model provider
obot-platform/tools pull request #297
Opened 2024-12-23 10:17 UTC by iwilltry42

2025-01-06 18:00 UTC, thedadams commented
My concern with this is that it is not `async` which we have seen performance issues with non-async model providers.

I noticed that there is a Go package: https://github.com/googleapis/go-genai

In your opinion, would this work for us?

2025-01-07 20:08 UTC, iwilltry42 commented
Back to draft for the rewrite to Go...

2025-01-09 18:57 UTC, iwilltry42 commented
Go Rewrite is done, but I'll continue implementing the embeddings API as well

2025-01-10 12:10 UTC, iwilltry42 commented
With the Go rewrite, I also added non-streaming responses and the /embeddings endpoint (needed a custom implementation as it's not part of their SDK and I couldn't get it working with what they have there so far... I re-used a bunch of code from knowledge, so it's fine).

2025-01-10 17:50 UTC, thedadams requested changes
A bunch of nits, but I there are a couple comments that should be addressed.

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/main.go
> +
nit:
```suggestion
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/main.go
> +		os.Exit(1)
We probably don't want to always `exit 1` for `validate.

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +
nit:
```suggestion
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +	mux.HandleFunc("/v1/embeddings", s.embeddings)
```suggestion
	mux.HandleFunc("GET /v1/models", s.listModels)
	mux.HandleFunc("POST /v1/chat/completions", s.chatCompletions)
	mux.HandleFunc("POST /v1/embeddings", s.embeddings)
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +
nit:
```suggestion
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +	content := ""
nit: I just think this looks nicer.
```suggestion
	var (
		toolCalls []openai.ToolCall
		content string
	)
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +		tidx := idx
This work-around isn't necessary as of Go 1.24.

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +
nit: not necessary

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +
nit:
```suggestion
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +func mapToOpenAIChoice(candidates []*genai.Candidate) ([]openai.ChatCompletionChoice, error) {
Same nits on this function

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +
nit:
```suggestion
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +
nit:
```suggestion
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +		http.Error(w, fmt.Sprintf("unexpected status code: %d", resp.StatusCode), http.StatusInternalServerError)
Does this make sense?
```suggestion
		http.Error(w, fmt.Sprintf("unexpected status code: %d", resp.StatusCode), resp.StatusCode)
```

2025-01-10 17:50 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +	}
Can we combine these with `json.NewDecoder(resp.Body).Decode(&embeddingResponse)`?

2025-01-13 08:43 UTC, iwilltry42 commented on gemini-vertex-model-provider/main.go
> +		os.Exit(1)
Probably

2025-01-13 08:47 UTC, iwilltry42 commented on gemini-vertex-model-provider/server/server.go
> +		http.Error(w, fmt.Sprintf("unexpected status code: %d", resp.StatusCode), http.StatusInternalServerError)
On the one hand yes to make it more transparent (as if we were just proxying) - but then again the message "unexpected status code" doesn't make sense anymore. Still I think you're right and it's better to hand through the resp.StatusCode.

2025-01-15 14:21 UTC, thedadams reviewed
Looks good! Adding usages is the last thing I can see.

2025-01-15 14:21 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +		"data": []map[string]any{
Can we add the `usage` metadata to these?

2025-01-15 14:21 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +	return
nit:
```suggestion
```

2025-01-15 14:21 UTC, thedadams commented on gemini-vertex-model-provider/server/server.go
> +	return
nit:
```suggestion
```

2025-01-17 11:28 UTC, iwilltry42 commented on gemini-vertex-model-provider/server/server.go
> +		"data": []map[string]any{
Done

2025-01-17 14:12 UTC, thedadams commented on gemini-vertex-model-provider/tool.gpt
> +Credential: ../model-provider-credential as gemini-vertex-model-provider
Sorry. After I approved I remembered this:
```suggestion
Credential: ../model-provider-credential as gemini-vertex-model-provider
Metadata: noUserAuth: gemini-vertex-model-provider
```

2025-01-17 14:56 UTC, merged